#lang racket
(display "Вариант 1\n")
(display "Вычисляем площадь кольца.\n")
(display "Введите радиус кольца и отверстия:\n")
(display "Радиус кольца(см) = ")
(define ring(read))
(display "Радиус отверстия(см) = ")
(define hole(read))
(define (s x y)
  (- (* 3.14 (* x x)) (* 3.14 (* y y))))
(if (> hole ring)
    (display "Ошибка, радиус отверстия не может быть больше радиуса кольца.\n\n")
    (display (format "Площадь кольца: ~a см. кв\n\n" (s ring hole))))

(display "\n\nВариант2 2\n")
(display "Определение високосности года \n")
(display "Введите год => ")
(define year(read))
(define (isLeap year)
  (
   cond ((= (remainder year 400) 0) (display "Год високосный"))
        ((= (remainder year 100) 0) (display "Год невисокосный"))
        ((= (remainder year 4) 0) (display "Год високосный"))
        (else (display "Год невисокосный"))
   )
  )
(isLeap year)

(display "Вариант 4\n")
(display "Вычисление сопротивления электрической цепи.\n")
(display "Введите исходные данные:\n")
(display "Величина первого сопротивления(Ом) = ")
(define R1(read))
(display "Величина второго сопротивления(Ом) = ")
(define R2(read))
(display "Укажите тип соединения (1 - последовательное, 2 - паралельное) = ")
(define type(read))
(define (parallel x y)
  (/ 1 (+ (/ 1 x) (/ 1 y))))
(define (consistent x y)
  (+ x y))
(define (R x y z)
  (cond ((= z 1) (consistent x y))
        ((= z 2) (parallel x y))))
(display (format "Сопротивление цепи: ~a Ом\n\n" (R R1 R2 type)))



